export const SET_PRODUCTS = 'SET_PRODUCT'
export const SET_RELATED_PRODUCTS = 'SET_RELATED_PRODUCTS'
export const GET_AUTH_DETAILS = 'GET_AUTH_DETAILS'
export const GET_LOCATION_STATE = 'GET_LOCATION_STATE'
